IDS, = glob_wildcards('input/{file,\w+}')

rule all:
    input: expand('output/{file}', file=IDS)
    output: touch('.status')

rule copy:
    input: 'input/{file}'
    output: 'output/{file}'
    shell: 'echo "Hello ""$(cat {input})""!" > {output}'